import { styled } from "panda/jsx";

import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <styled.body bgColor={"gray.900"}>{children}</styled.body>
    </html>
  );
}
